# Generated by Django 3.0.8 on 2020-07-28 17:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=6400)),
                ('likes', models.IntegerField(default=0)),
                ('date_created', models.DateTimeField()),
                ('date_modified', models.DateTimeField()),
                ('is_modified', models.BooleanField(default=False)),
                ('user_p', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_p', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
