# Generated by Django 3.0.8 on 2020-08-03 20:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0010_likes_post_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likes',
            name='users',
        ),
        migrations.AddField(
            model_name='likes',
            name='users',
            field=models.ManyToManyField(related_name='users', to=settings.AUTH_USER_MODEL),
        ),
    ]
