# Generated by Django 3.0.8 on 2020-08-03 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0011_auto_20200803_2026'),
    ]

    operations = [
        migrations.AddField(
            model_name='likes',
            name='is_liked',
            field=models.BooleanField(default=False),
        ),
    ]
