# Generated by Django 3.0.8 on 2020-08-18 20:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0014_auto_20200815_0251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_followers',
            name='follower_id',
        ),
        migrations.AddField(
            model_name='user_followers',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='followers', to=settings.AUTH_USER_MODEL),
        ),
    ]
