# Generated by Django 3.0.8 on 2020-08-19 17:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0015_auto_20200818_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_followers',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='following', to=settings.AUTH_USER_MODEL),
        ),
    ]
